// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/treeNode.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2ftreeNode_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_proto_2ftreeNode_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2ftreeNode_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2ftreeNode_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_proto_2ftreeNode_2eproto;
class TreeNode;
struct TreeNodeDefaultTypeInternal;
extern TreeNodeDefaultTypeInternal _TreeNode_default_instance_;
class TreeNodeList;
struct TreeNodeListDefaultTypeInternal;
extern TreeNodeListDefaultTypeInternal _TreeNodeList_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template <>
::TreeNode* Arena::CreateMaybeMessage<::TreeNode>(Arena*);
template <>
::TreeNodeList* Arena::CreateMaybeMessage<::TreeNodeList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE


// ===================================================================


// -------------------------------------------------------------------

class TreeNode final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TreeNode) */ {
 public:
  inline TreeNode() : TreeNode(nullptr) {}
  ~TreeNode() override;
  explicit PROTOBUF_CONSTEXPR TreeNode(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TreeNode(const TreeNode& from);
  TreeNode(TreeNode&& from) noexcept
    : TreeNode() {
    *this = ::std::move(from);
  }

  inline TreeNode& operator=(const TreeNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline TreeNode& operator=(TreeNode&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TreeNode& default_instance() {
    return *internal_default_instance();
  }
  static inline const TreeNode* internal_default_instance() {
    return reinterpret_cast<const TreeNode*>(
               &_TreeNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TreeNode& a, TreeNode& b) {
    a.Swap(&b);
  }
  inline void Swap(TreeNode* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TreeNode* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TreeNode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TreeNode>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TreeNode& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TreeNode& from) {
    TreeNode::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TreeNode* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "TreeNode";
  }
  protected:
  explicit TreeNode(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBloomFilterFieldNumber = 11,
    kLevelFieldNumber = 1,
    kChildSizeFieldNumber = 2,
    kMinxFieldNumber = 3,
    kMaxxFieldNumber = 4,
    kMinyFieldNumber = 5,
    kMaxyFieldNumber = 6,
    kMinzFieldNumber = 7,
    kMaxzFieldNumber = 8,
    kStartFieldNumber = 9,
    kEndFieldNumber = 10,
  };
  // bytes bloom_filter = 11;
  void clear_bloom_filter() ;
  const std::string& bloom_filter() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_bloom_filter(Arg_&& arg, Args_... args);
  std::string* mutable_bloom_filter();
  PROTOBUF_NODISCARD std::string* release_bloom_filter();
  void set_allocated_bloom_filter(std::string* ptr);

  private:
  const std::string& _internal_bloom_filter() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bloom_filter(
      const std::string& value);
  std::string* _internal_mutable_bloom_filter();

  public:
  // int32 level = 1;
  void clear_level() ;
  ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // int32 childSize = 2;
  void clear_childsize() ;
  ::int32_t childsize() const;
  void set_childsize(::int32_t value);

  private:
  ::int32_t _internal_childsize() const;
  void _internal_set_childsize(::int32_t value);

  public:
  // double minx = 3;
  void clear_minx() ;
  double minx() const;
  void set_minx(double value);

  private:
  double _internal_minx() const;
  void _internal_set_minx(double value);

  public:
  // double maxx = 4;
  void clear_maxx() ;
  double maxx() const;
  void set_maxx(double value);

  private:
  double _internal_maxx() const;
  void _internal_set_maxx(double value);

  public:
  // double miny = 5;
  void clear_miny() ;
  double miny() const;
  void set_miny(double value);

  private:
  double _internal_miny() const;
  void _internal_set_miny(double value);

  public:
  // double maxy = 6;
  void clear_maxy() ;
  double maxy() const;
  void set_maxy(double value);

  private:
  double _internal_maxy() const;
  void _internal_set_maxy(double value);

  public:
  // double minz = 7;
  void clear_minz() ;
  double minz() const;
  void set_minz(double value);

  private:
  double _internal_minz() const;
  void _internal_set_minz(double value);

  public:
  // double maxz = 8;
  void clear_maxz() ;
  double maxz() const;
  void set_maxz(double value);

  private:
  double _internal_maxz() const;
  void _internal_set_maxz(double value);

  public:
  // uint64 start = 9;
  void clear_start() ;
  ::uint64_t start() const;
  void set_start(::uint64_t value);

  private:
  ::uint64_t _internal_start() const;
  void _internal_set_start(::uint64_t value);

  public:
  // uint64 end = 10;
  void clear_end() ;
  ::uint64_t end() const;
  void set_end(::uint64_t value);

  private:
  ::uint64_t _internal_end() const;
  void _internal_set_end(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:TreeNode)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bloom_filter_;
    ::int32_t level_;
    ::int32_t childsize_;
    double minx_;
    double maxx_;
    double miny_;
    double maxy_;
    double minz_;
    double maxz_;
    ::uint64_t start_;
    ::uint64_t end_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ftreeNode_2eproto;
};// -------------------------------------------------------------------

class TreeNodeList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TreeNodeList) */ {
 public:
  inline TreeNodeList() : TreeNodeList(nullptr) {}
  ~TreeNodeList() override;
  explicit PROTOBUF_CONSTEXPR TreeNodeList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TreeNodeList(const TreeNodeList& from);
  TreeNodeList(TreeNodeList&& from) noexcept
    : TreeNodeList() {
    *this = ::std::move(from);
  }

  inline TreeNodeList& operator=(const TreeNodeList& from) {
    CopyFrom(from);
    return *this;
  }
  inline TreeNodeList& operator=(TreeNodeList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TreeNodeList& default_instance() {
    return *internal_default_instance();
  }
  static inline const TreeNodeList* internal_default_instance() {
    return reinterpret_cast<const TreeNodeList*>(
               &_TreeNodeList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TreeNodeList& a, TreeNodeList& b) {
    a.Swap(&b);
  }
  inline void Swap(TreeNodeList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TreeNodeList* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TreeNodeList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TreeNodeList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TreeNodeList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TreeNodeList& from) {
    TreeNodeList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TreeNodeList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "TreeNodeList";
  }
  protected:
  explicit TreeNodeList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTreeNodesFieldNumber = 1,
  };
  // repeated .TreeNode treeNodes = 1;
  int treenodes_size() const;
  private:
  int _internal_treenodes_size() const;

  public:
  void clear_treenodes() ;
  ::TreeNode* mutable_treenodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TreeNode >*
      mutable_treenodes();
  private:
  const ::TreeNode& _internal_treenodes(int index) const;
  ::TreeNode* _internal_add_treenodes();
  public:
  const ::TreeNode& treenodes(int index) const;
  ::TreeNode* add_treenodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TreeNode >&
      treenodes() const;
  // @@protoc_insertion_point(class_scope:TreeNodeList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TreeNode > treenodes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ftreeNode_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TreeNode

// int32 level = 1;
inline void TreeNode::clear_level() {
  _impl_.level_ = 0;
}
inline ::int32_t TreeNode::level() const {
  // @@protoc_insertion_point(field_get:TreeNode.level)
  return _internal_level();
}
inline void TreeNode::set_level(::int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:TreeNode.level)
}
inline ::int32_t TreeNode::_internal_level() const {
  return _impl_.level_;
}
inline void TreeNode::_internal_set_level(::int32_t value) {
  ;
  _impl_.level_ = value;
}

// int32 childSize = 2;
inline void TreeNode::clear_childsize() {
  _impl_.childsize_ = 0;
}
inline ::int32_t TreeNode::childsize() const {
  // @@protoc_insertion_point(field_get:TreeNode.childSize)
  return _internal_childsize();
}
inline void TreeNode::set_childsize(::int32_t value) {
  _internal_set_childsize(value);
  // @@protoc_insertion_point(field_set:TreeNode.childSize)
}
inline ::int32_t TreeNode::_internal_childsize() const {
  return _impl_.childsize_;
}
inline void TreeNode::_internal_set_childsize(::int32_t value) {
  ;
  _impl_.childsize_ = value;
}

// double minx = 3;
inline void TreeNode::clear_minx() {
  _impl_.minx_ = 0;
}
inline double TreeNode::minx() const {
  // @@protoc_insertion_point(field_get:TreeNode.minx)
  return _internal_minx();
}
inline void TreeNode::set_minx(double value) {
  _internal_set_minx(value);
  // @@protoc_insertion_point(field_set:TreeNode.minx)
}
inline double TreeNode::_internal_minx() const {
  return _impl_.minx_;
}
inline void TreeNode::_internal_set_minx(double value) {
  ;
  _impl_.minx_ = value;
}

// double maxx = 4;
inline void TreeNode::clear_maxx() {
  _impl_.maxx_ = 0;
}
inline double TreeNode::maxx() const {
  // @@protoc_insertion_point(field_get:TreeNode.maxx)
  return _internal_maxx();
}
inline void TreeNode::set_maxx(double value) {
  _internal_set_maxx(value);
  // @@protoc_insertion_point(field_set:TreeNode.maxx)
}
inline double TreeNode::_internal_maxx() const {
  return _impl_.maxx_;
}
inline void TreeNode::_internal_set_maxx(double value) {
  ;
  _impl_.maxx_ = value;
}

// double miny = 5;
inline void TreeNode::clear_miny() {
  _impl_.miny_ = 0;
}
inline double TreeNode::miny() const {
  // @@protoc_insertion_point(field_get:TreeNode.miny)
  return _internal_miny();
}
inline void TreeNode::set_miny(double value) {
  _internal_set_miny(value);
  // @@protoc_insertion_point(field_set:TreeNode.miny)
}
inline double TreeNode::_internal_miny() const {
  return _impl_.miny_;
}
inline void TreeNode::_internal_set_miny(double value) {
  ;
  _impl_.miny_ = value;
}

// double maxy = 6;
inline void TreeNode::clear_maxy() {
  _impl_.maxy_ = 0;
}
inline double TreeNode::maxy() const {
  // @@protoc_insertion_point(field_get:TreeNode.maxy)
  return _internal_maxy();
}
inline void TreeNode::set_maxy(double value) {
  _internal_set_maxy(value);
  // @@protoc_insertion_point(field_set:TreeNode.maxy)
}
inline double TreeNode::_internal_maxy() const {
  return _impl_.maxy_;
}
inline void TreeNode::_internal_set_maxy(double value) {
  ;
  _impl_.maxy_ = value;
}

// double minz = 7;
inline void TreeNode::clear_minz() {
  _impl_.minz_ = 0;
}
inline double TreeNode::minz() const {
  // @@protoc_insertion_point(field_get:TreeNode.minz)
  return _internal_minz();
}
inline void TreeNode::set_minz(double value) {
  _internal_set_minz(value);
  // @@protoc_insertion_point(field_set:TreeNode.minz)
}
inline double TreeNode::_internal_minz() const {
  return _impl_.minz_;
}
inline void TreeNode::_internal_set_minz(double value) {
  ;
  _impl_.minz_ = value;
}

// double maxz = 8;
inline void TreeNode::clear_maxz() {
  _impl_.maxz_ = 0;
}
inline double TreeNode::maxz() const {
  // @@protoc_insertion_point(field_get:TreeNode.maxz)
  return _internal_maxz();
}
inline void TreeNode::set_maxz(double value) {
  _internal_set_maxz(value);
  // @@protoc_insertion_point(field_set:TreeNode.maxz)
}
inline double TreeNode::_internal_maxz() const {
  return _impl_.maxz_;
}
inline void TreeNode::_internal_set_maxz(double value) {
  ;
  _impl_.maxz_ = value;
}

// uint64 start = 9;
inline void TreeNode::clear_start() {
  _impl_.start_ = ::uint64_t{0u};
}
inline ::uint64_t TreeNode::start() const {
  // @@protoc_insertion_point(field_get:TreeNode.start)
  return _internal_start();
}
inline void TreeNode::set_start(::uint64_t value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:TreeNode.start)
}
inline ::uint64_t TreeNode::_internal_start() const {
  return _impl_.start_;
}
inline void TreeNode::_internal_set_start(::uint64_t value) {
  ;
  _impl_.start_ = value;
}

// uint64 end = 10;
inline void TreeNode::clear_end() {
  _impl_.end_ = ::uint64_t{0u};
}
inline ::uint64_t TreeNode::end() const {
  // @@protoc_insertion_point(field_get:TreeNode.end)
  return _internal_end();
}
inline void TreeNode::set_end(::uint64_t value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:TreeNode.end)
}
inline ::uint64_t TreeNode::_internal_end() const {
  return _impl_.end_;
}
inline void TreeNode::_internal_set_end(::uint64_t value) {
  ;
  _impl_.end_ = value;
}

// bytes bloom_filter = 11;
inline void TreeNode::clear_bloom_filter() {
  _impl_.bloom_filter_.ClearToEmpty();
}
inline const std::string& TreeNode::bloom_filter() const {
  // @@protoc_insertion_point(field_get:TreeNode.bloom_filter)
  return _internal_bloom_filter();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TreeNode::set_bloom_filter(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.bloom_filter_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TreeNode.bloom_filter)
}
inline std::string* TreeNode::mutable_bloom_filter() {
  std::string* _s = _internal_mutable_bloom_filter();
  // @@protoc_insertion_point(field_mutable:TreeNode.bloom_filter)
  return _s;
}
inline const std::string& TreeNode::_internal_bloom_filter() const {
  return _impl_.bloom_filter_.Get();
}
inline void TreeNode::_internal_set_bloom_filter(const std::string& value) {
  ;


  _impl_.bloom_filter_.Set(value, GetArenaForAllocation());
}
inline std::string* TreeNode::_internal_mutable_bloom_filter() {
  ;
  return _impl_.bloom_filter_.Mutable( GetArenaForAllocation());
}
inline std::string* TreeNode::release_bloom_filter() {
  // @@protoc_insertion_point(field_release:TreeNode.bloom_filter)
  return _impl_.bloom_filter_.Release();
}
inline void TreeNode::set_allocated_bloom_filter(std::string* value) {
  _impl_.bloom_filter_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.bloom_filter_.IsDefault()) {
          _impl_.bloom_filter_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TreeNode.bloom_filter)
}

// -------------------------------------------------------------------

// TreeNodeList

// repeated .TreeNode treeNodes = 1;
inline int TreeNodeList::_internal_treenodes_size() const {
  return _impl_.treenodes_.size();
}
inline int TreeNodeList::treenodes_size() const {
  return _internal_treenodes_size();
}
inline void TreeNodeList::clear_treenodes() {
  _impl_.treenodes_.Clear();
}
inline ::TreeNode* TreeNodeList::mutable_treenodes(int index) {
  // @@protoc_insertion_point(field_mutable:TreeNodeList.treeNodes)
  return _impl_.treenodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TreeNode >*
TreeNodeList::mutable_treenodes() {
  // @@protoc_insertion_point(field_mutable_list:TreeNodeList.treeNodes)
  return &_impl_.treenodes_;
}
inline const ::TreeNode& TreeNodeList::_internal_treenodes(int index) const {
  return _impl_.treenodes_.Get(index);
}
inline const ::TreeNode& TreeNodeList::treenodes(int index) const {
  // @@protoc_insertion_point(field_get:TreeNodeList.treeNodes)
  return _internal_treenodes(index);
}
inline ::TreeNode* TreeNodeList::_internal_add_treenodes() {
  return _impl_.treenodes_.Add();
}
inline ::TreeNode* TreeNodeList::add_treenodes() {
  ::TreeNode* _add = _internal_add_treenodes();
  // @@protoc_insertion_point(field_add:TreeNodeList.treeNodes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TreeNode >&
TreeNodeList::treenodes() const {
  // @@protoc_insertion_point(field_list:TreeNodeList.treeNodes)
  return _impl_.treenodes_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_proto_2ftreeNode_2eproto_2epb_2eh
